garmeeh/next-seo

README.md, e2e/cypress/e2e/jsonld.spec.js, e2e/cypress/schemas/index.js, e2e/cypress/schemas/local-business-schema.js, e2e/pages/jsonld.jsx, src/index.js, src/jsonld/localBusiness.jsx
This adds support for[ basic local business](https://developers.google.com/search/docs/data-types/local-business) properties as outlined in the readme. 
By default the type will be LocalBusiness but users can provide any valid sub-type as per the documentation. 
Images code was taken from product but not turned into a generic helper. This felt like it could be reused but leaving them separate allowed for better isolation. Happy to change this and move buildImages to a common builders file with tests. 
Additional changes to reorder imports/exports alphabetically and add the missing product link in the readme are included in the same commit.   
Fixes #23
=> Add JSON-LD Local Business

README.md, e2e/cypress/e2e/seo.spec.js, e2e/next-seo.config.js, e2e/pages/overridden.jsx, src/meta/__tests__/__snapshots__/buildTags.spec.jsx.snap, src/meta/__tests__/buildTags.spec.jsx, src/meta/buildTags.jsx
This metadata is used to enable facebook insights to work on your site: https://developers.facebook.com/docs/sharing/webmasters/#markup
You can see sites like amazon and twitch using this in markup as well (out of curiosity I checked a few sites), and if you google it you'll see requests for website building tools to support this.
(sorry about duplicate PR that I just closed on this - the commit history was messed up)
=> Support facebook meta (fb:app_id) to enable Facebook Insights

e2e/cypress/e2e/seo.spec.js, src/meta/__tests__/__snapshots__/buildTags.spec.jsx.snap, src/meta/__tests__/buildTags.spec.jsx, src/meta/buildTags.jsx
Close #43, According to facebook debug tool
`property='fb:app_id'` should be used instead of `name='fb:app_id'`
=>  property='fb:app_id' should be used instead of name='fb:app_id'

README.md
Due to both OpenGraph and JSON-LD having `Article` links when you click the article link in JSON-LD it routes to the Open Graph `Article`. This slight update fixes the issue.
=> Fix link issue with Article

README.md
These get interpreted as HTML tags by the markdown renderer.
=> Fix display of jsx tags in readme

README.md
hello - I upgraded one of my projects to next.js to v9.5 and next-seo 2.1.0 and these were a couple things I noticed / had to debug. Particularly I was getting an import error - but the output / error was being logged in my _document.js so it was not obvious where my problem was (I did not realize it was next-seo causing this error in the first place).  So if you want and think it can be useful, this note may help people in the future upgrading from v1 to v2.  Otherwise the upgrade seems good to me
=> documentation for next.js v9.0+ and next-seo v2+ upgrade tips

src/jsonld/product.tsx
Rating and aggregated reviews are non-required fields (but recommended) according to Google documentations and looks like it also handled by codebase. 
So I just tuned up a type for component props.
Sometimes you can have a product on your website but you can have no reviews or ratings for products.
https://developers.google.com/search/docs/data-types/product
=> Rating and reviews are non-required fields

README.md, cypress/e2e/jsonld.spec.js, cypress/schemas/local-business-schema.js, e2e/pages/jsonld.tsx, src/jsonld/localBusiness.tsx
closes https://github.com/garmeeh/next-seo/issues/111
-adds support for openingHoursSpecification (some info here https://developers.google.com/search/docs/data-types/local-business) and sameAs for local business jsonld
-openingHours can be provided as a single object or array of objects as suggested on the google page above
-added missing documentation for rating and pricerange
=> Opening hours and sameAs support for local business jsonld

README.md
Removed initial props from documentation.
This is currently giving warning from next since it turns off Automatic Static Optimization.
https://github.com/zeit/next.js/blob/master/errors/opt-out-auto-static-optimization.md
=> Removed initial props from readme.

README.md
In this PR https://github.com/garmeeh/next-seo/pull/142 the documentation for JobPosting was added in the middle of faq page.
This will bring the faq page documentation together again.
=> Moved props in redme for faqpage.

e2e/pages/_app.tsx
Removed get initial props from test app.
Since this is not the "standard" way of running a next app anymore.
=> Removed getInitialProps from e2e test app.

.babelrc
Change `next/babel` options and don't use `@babel/runtime-corejs2`. This will allow you to build Next.js v9.2.3 without any problems.
Resolve #178
=> Disable use `@babel/runtime-corejs2`

README.md, cypress/e2e/jsonld.spec.js, cypress/schemas/common.js, cypress/schemas/product-schema.js, e2e/pages/jsonld.tsx, src/jsonld/product.tsx
closes #132 
Allows multiple offers to be provided as an array in product json LD (https://schema.org/Offer example 8 JSON-ld example shows that this should be supported). With this change there is still compatibility for providing the offer as a single object
=> add support for multiple offers in product jsonld

src/jsonld/article.tsx, src/jsonld/blog.tsx, src/jsonld/breadcrumb.tsx, src/jsonld/corporateContact.tsx, src/jsonld/course.tsx, src/jsonld/dataset.tsx, src/jsonld/event.tsx, src/jsonld/faqPage.tsx, src/jsonld/jobPosting.tsx, src/jsonld/localBusiness.tsx, src/jsonld/logo.tsx, src/jsonld/newsarticle.tsx, src/jsonld/product.tsx, src/jsonld/recipe.tsx, src/jsonld/socialProfile.tsx, src/utils/minifyJsonLd.ts
Minifies the jsonLd content before rendering it on `<Head>`
I'm not entirely sure if this is the most efficient way of doing this, but definitely reliable and doesn't add any extra deps. I'd rather have the extra computational work than no compression at all. 
Closes https://github.com/garmeeh/next-seo/issues/263#issue-592275986
---
Not sure if it should be mentioned anywhere in the docs, up to suggestions. Would be no problem to do it
Didn't find any jsonLd related unit tests, and I didn't write any
Didn't write it but I tested on the test app and also ran cypress …
=> feat(minify-json-ld): minifies jsonLd output

README.md
It looks `languageAlternates` is right(not `languageAlternate`), am I correct?
=> update outdated doc

README.md, cypress/e2e/jsonld.spec.js, e2e/components/links.tsx, e2e/pages/carousel-jsonld/course.tsx, e2e/pages/carousel-jsonld/default.tsx, e2e/pages/carousel-jsonld/movie.tsx, e2e/pages/carousel-jsonld/recipe.tsx, src/index.tsx, src/jsonld/carousel.tsx, src/jsonld/product.tsx, src/jsonld/recipe.tsx
Implements #415 
Adds the carousel jsonld component. Refer here- https://developers.google.com/search/docs/data-types/carousel
The following types are currently supported: 
- Default (the summary list)
- Course
- Movie
- Recipe
Have updated all the e2e cypress tests and the docs in the README
=> Add carousel jsonld

README.md
Just a quick README update – was confused initially as your documentation shows `appId` as a number, but it requires a string.
=> Update Facebook appId to be a string in README.md

README.md
Generally, Next.js recommend the use of named components.
https://github.com/vercel/next.js/issues/17200
https://github.com/vercel/next.js/blob/f8aeaa479ecaaccd4807db42e8df256aa813b194/packages/next/build/babel/plugins/no-anonymous-default-export.ts#L41
> Anonymous arrow functions cause Fast Refresh to not preserve local component state.
---
`import React from 'react';` isn't necessary.
https://github.com/vercel/next.js/pull/16603
=> [README] Named components and remove 'import react'

README.md, cypress/e2e/jsonld.spec.js, cypress/schemas/index.js, cypress/schemas/qa-page-schema.js, e2e/pages/jsonld.tsx, src/index.tsx, src/jsonld/qaPage.tsx
The addition of the [Q&A DataType](https://developers.google.com/search/docs/data-types/qapage) to handle questions and answers with the JSON-LD scripts.
Progress:
---
- Have you updated the documentation to go with your changes? **Yes, added all the documentation for all Q&A props** 
- Have you written or updated unit tests? **No**
- Have you written an integration test in the test app supplied? **Yes, I've written e2e tests for the Q&A Page JSON-LD**
=> [Feature] Q&A datatype support

README.md
- Added `sameAs` prop to LocalBusinessJsonLd component in Readme
=> LocalBusinessJsonLd sameAs prop added to Readme

README.md
Readme: Version numbers 6.0.0 - 7.0.0-canary.0 unclear #611
Changed _is only available in version `7.0.0-canary.0`+_ to _is available from next.js version `7.0.0-canary.0`_ in 5 places.
- Have you updated the documentation to go with your changes? **Documentation only change**
- Have you written or updated unit tests? **No functional change**
- Have you written an integration test in the test app supplied? **No functional change**
=> Readme: Version numbers unclear #611

README.md, cypress/e2e/seo.spec.js, e2e/pages/overridden.tsx, src/meta/__tests__/buildTags.spec.tsx, src/meta/buildTags.tsx, src/types.ts
Add `httpEquiv` to `additionalMetaTags`
Close #535
---
- Have you updated the documentation to go with your changes? Yes
- Have you written or updated unit tests? Yes
- Have you written an integration test in the test app supplied? Yes
=> fix: add httpEquiv to additionalMetaTags

README.md, src/meta/__tests__/buildTags.spec.tsx, src/meta/buildTags.tsx, src/types.ts
This change causes a `<title>` tag to be rendered if no `config.title` is provided but a `config.defaultTitle` is. It skips the templating step and renders the `defaultTitle` as is.
Fixes #366
=> Support a defaultTitle config option

README.md, cypress/e2e/seo.spec.js, e2e/next-seo.config.ts, e2e/pages/overridden.tsx, src/meta/__tests__/__snapshots__/buildTags.spec.tsx.snap, src/meta/__tests__/buildTags.spec.tsx, src/meta/buildTags.tsx, src/meta/defaultSEO.tsx, src/meta/nextSEO.tsx, src/types.ts
Closes: https://github.com/garmeeh/next-seo/issues/182
This PR adds `additionalLinkTags` to config.
Since link tags are used for icons, manifest, and so on which are really important for SEO, this should be included in config.
---
- Have you updated the documentation to go with your changes? :white_check_mark:
- Have you written or updated unit tests? :white_check_mark:
- Have you written an integration test in the test app supplied? :white_check_mark:
=> Add additionalLinkTags

README.md, cypress/e2e/jsonld.spec.js, e2e/pages/jsonld.tsx, src/jsonld/product.tsx
Adds support for a few currently missing options in ProductJsonLd
Following the spec https://schema.org/Product
Adds:
* color
* manufacturerName
* manufacturerLogo
* material
* slogan
* disambiguatingDescription
* releaseDate
* productionDate
* purchaseDate
* award
Other: 
- Updated Product in README to reflect changes
- Updated  tests to reflect changes
=> Extend props for ProductJsonLd component

cypress/e2e/jsonld.spec.js, cypress/schemas/common.js, e2e/pages/jsonld.tsx, src/jsonld/product.tsx, src/jsonld/recipe.tsx
---
This PR contains a fix of #698 
There were some missing **aggregateRating** fields: `bestRating` `ratingCount`
**Docs:**
https://schema.org/aggregateRating
https://developers.google.com/search/docs/data-types/product
=> fix: missing aggregate rating fields

e2e/pages/overridden.tsx, src/meta/buildTags.tsx, src/types.ts
Fix #347 
---
Not yet
I couldn't find tests about `og:video`. Should i write some ? Maybe in another PR ?
Same than above
=> WIP :sparkles: Add og:video:secure_url and og:video:type

README.md, cypress/e2e/jsonld.spec.js, cypress/schemas/product-schema.js, e2e/components/links.tsx, e2e/pages/product-jsonld/aggregateOffer.tsx, e2e/pages/product-jsonld/aggregateOffer2.tsx, e2e/pages/product-jsonld/aggregateOfferAndOffers.tsx, e2e/pages/product-jsonld/offers.tsx, src/jsonld/product.tsx, src/types.ts, src/utils/buildAggregateOffer.ts
Closes: #766.
- New test to check if both `offers` and `aggregateOffer` are provided in product ld-json, the `aggregateOffer` is ignored.
- New test to check product ld-json `aggregateOffer` separately
- New test to check product ld-json `offers` separately
- This PR also includes a fix of not set fields show up which are `images` and `manufacturer` in product ld-json in the output.
=> fix: missing offers field in aggregateOffer

cypress/e2e/seo.spec.js, e2e/next-env.d.ts, e2e/pages/overridden/titleWithoutOpenGraph.tsx, src/meta/__tests__/__snapshots__/buildTags.spec.tsx.snap, src/meta/buildTags.tsx
Fixes https://github.com/garmeeh/next-seo/issues/544 , `og:title` & `og:description` can now be overridden by `<NextSeo>` when `openGraph` prop exists on `<DefaultSeo>`
- **Have you updated the documentation to go with your changes?** 
Bug fix, this change doesn't require documentation update
- **Have you written or updated unit tests?**
Updated snapshots
- **Have you written an integration test in the test app supplied?**
Added a new integration test
=> fix(NextSeo): og:title and og:description are not overridden #544

README.md
I search for document about Twitter SEO with Twitter props name (i.e: "twitter:site", "twitter card site seo") but got very misleading result.
Beside my change in this `README.md`, I suggest change prop `handler` name --> `creator`.
Props `cardType`, `site`, `handle` are equivalent to `twitter:card`, `twitter:site`, `twitter:creator`. Documentation can be founded [here](https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/summary).
--- …
=> More notes on Twitter props

README.md
`--save` flag is no longer needed with npm: https://blog.npmjs.org/post/161081169345/v500
=> --save flag is not needed with npm any more

CONTRIBUTING.md
[e2e:dev](https://github.com/garmeeh/next-seo/blob/4776325a473df40207efef99d32bcfa6243766ee/package.json#L36) is defined under the scripts option in the `package.json` file but there is no ~e2eL:dev~ listed.
Most likely a typo or a missed script inclusion.
=> Fix typo - yarn e2e:dev instead of yarn e2eL:dev

babel.config.js
Relates: #932
Current Babel config target is too strict, it doesn't include `?.` operator polyfill. As a result, older browsers fail to compile source code and throw Syntax errors.
This PR updates Babel targets to be less strict and include polyfills for older browsers.
New `targets` config is the default Babel recommendation `> 0.25%, not dead`,
and is taken directly from https://babeljs.io/docs/en/babel-preset-env#browserslist-integration
=> #932 Update Babel config to include polyfill for older browsers

README.md, cypress/e2e/event.spec.js, cypress/e2e/virtualEvent.spec.js, e2e/pages/jsonld/event.tsx, e2e/pages/jsonld/virtualEvent.tsx, src/jsonld/event.tsx, src/types.ts, src/utils/schema/setLocation.ts, src/utils/schema/setOrganizer.ts, src/utils/schema/setPerformer.ts
Hey maintainers! First of all, thanks for this awesome plugin. This is my first time contributing, I needed some more properties and wanted to keep on using this plugin rather than write them out by hand on a script tag. I tried to follow all the guidelines, if there's anything else you need me to do to get this merged I'll follow!
Extended `EventJsonLd` to accept more properties:
- Location can now be a `VirtualLocation` as well as a `Place`
- Added `organizer`, `eventStatus` and `eventAttendanceMode`
- Performers can be both `Person` or `PerformingGroup`
Updated documentation and tests to fit my changes.
=> Add more properties to JsonLd Event and allow VirtualLocation

README.md, cypress/e2e/jobPosting.spec.js, cypress/schemas/job-posting-schema.js, e2e/pages/jsonld/jobPosting.tsx, src/jsonld/jobPosting.tsx
This adds an `experienceRequirements` object on the `JobPostingJsonLd` component.
It includes options for occupational experience, educational experience and a boolean for whether experience is accepted in place of education or not.
---
[x] Updated the documentation
=> adds experience requirements for job posting

src/jsonld/jobPosting.tsx
---
[x] Updated the documentation
---
Not sure if valid through is allowed to be null/undefined, maybe we need to set it to a date such as 9999. But that seems ugly in my opinion.
=> fix(#957): Optional validThrough property for JobPostings

README.md, src/types.ts
Children property should be disabled as it is not supported by the NextSeo component. I've also added the note that the `additionalMetaTags` should be used for custom tags. Please let me know if tests are needed for this case.
---
=> disable children property from NextSeo as it is not supported

README.md, e2e/next-seo.config.ts, e2e/pages/article.tsx, e2e/pages/book.tsx, e2e/pages/overridden.tsx, e2e/pages/profile.tsx, e2e/pages/video.tsx, src/meta/__tests__/buildTags.spec.tsx, src/meta/buildTags.tsx, src/types.ts
ref: https://github.com/garmeeh/next-seo/issues/1011 I updated openGraph tag `site_name` per camel case convention `siteName`. 
I worked during hacktoberfest it's possibly to add label `hacktoberfest` 🙏 
---
[x] Updated the documentation
=> Add siteName next to site_name to respect camelCase convention

README.md
Fixes #900
The error reported on issue #900 it's not properly a bug.
This issue only happens when using TypeScript, and it's caused by type inference.
When using an external next-seo config file, TypeScript automatically infers `httpEquiv` as a `string` (a wider type).
The `httpEquiv` type extends a `string`. However, `string` does not extend `'content-type' | 'content-security-policy' | 'default-style'...` so it cannot be assigned to it.
The easiest and cleanest way to solve this is to declare the object type inside the config file.
So I've updated the documentation to give an example of the config file that needs to be used in a TypeScript project.
---
Please link to relevant Google Docs or schema.org docs for what you are …
=> fix: add docs example to avoid httpEquiv TypeScript error

README.md, cypress/e2e/article.spec.js, cypress/e2e/newsarticle.spec.js, cypress/schemas/article-schema.js, cypress/schemas/newsarticle-schema.js, e2e/pages/jsonld/article.tsx, e2e/pages/jsonld/newsarticle.tsx, src/jsonld/article.tsx, src/jsonld/newsarticle.tsx
Fixes #902
This property is really useful when working with paywalled articles.
Read more: [Paywalled Content](https://developers.google.com/search/docs/appearance/structured-data/paywalled-content).
---
=> feat: add isAccessibleForFree prop on article and newsarticle

cypress/e2e/organization.spec.js, cypress/schemas/organization-schema.js, e2e/pages/jsonld/organization/multipleAddresses.tsx, e2e/pages/jsonld/organization/organization.tsx, src/jsonld/organization.tsx
Fixes #925
As explained in the official schema.org docs:
> [contactPoints](https://schema.org/contactPoints) has been [superseded](https://schema.org/contactPoints#supersededby).
---
=> fix: organization prop contactPoint

APP_DIRECTORY.md
I couldn't figure out why the head wasn't re-rendering for an hour or more, thinking it was an issue with my build or `next-seo`. This warning could make it more obvious to others.
=> Update app directory documentation

README.md, src/meta/__tests__/buildTags.spec.tsx, src/meta/buildTags.tsx
Fixes #1079.
- Stops the `keyOverride` prop for `additionalMetaTags` being rendered as a `keyoverride` attribute.
- Improves the readme around the `keyOverride` prop
=> Remove keyoverride attribute from additional meta tags

src/jsonld/product.tsx
`Product` can have a single `Review`. This is actually what Google recommends.
https://developers.google.com/search/docs/appearance/structured-data/product#product-review-page-example
---
[ ] Updated the documentation
[ ] Unit/Cypress test covering all cases
=> fix: product can have a single review

src/jsonld/event.tsx
Fixes #1115 . Set `undefined` to `eventStatus`/`eventAttendanceMode` if they are not present.
---
[] ~Updated the documentation~
=> fix(EventJsonLd): Do not add `eventStatus`/`eventAttendanceMode` if not present

src/types.ts, src/utils/schema/__tests__/setAddress.test.ts, src/utils/schema/__tests__/setLocation.test.ts, src/utils/schema/setAddress.ts, src/utils/schema/setLocation.ts
Fixes #1116
- `type Location` now includes `string` (cf: [location](https://schema.org/location))
- `type Address` now includes `string` (cf: [address](https://schema.org/address))
- `setLocation()` and `setAddress` return string itself for parameters with type string
- Add unit tests
---
=> fix: Accept type string for `location` and `address`

e2e/pages/jsonld/index.tsx
There is a typo in e2e app `/jsonld`:
- :x: `even`
- :o: `event`
---
[] ~Updated the documentation~
[] ~Unit/Cypress test covering all cases~
=> fix: typo in e2e app

src/types.ts
Refs issue : https://github.com/garmeeh/next-seo/issues/975
---
[ ] Updated the documentation
[V] Unit/Cypress test covering all cases
=> chore: Allow null for TS definitions about width and height of OpenGraphMedia 

src/jsonld/newsarticle.tsx, src/types.ts, src/utils/schema/__tests__/setAuthor.test.ts, src/utils/schema/setAuthor.ts
`NewsArticleJsonLd` author couldn't be customised with `@type` and `url` parameter.
With this PR `NewsArticleJsonLd` `authorName` prop accepts also `ArticleAuthor`.
Also there was no way to override `@type` property of `author`. With this PR the default is set to `Person` but can be customised.
---
* https://schema.org/NewsArticle
* https://schema.org/author
=> feat: enhance NewsArticleJsonLd and ArticleJsonLd author

src/meta/__tests__/buildTags.spec.tsx, src/meta/buildTags.tsx
Fixes #727. 
`dangerouslySetAllPagesToNoIndex` in `<DefaultSeo>` had been having a priority over `noindex: false` in `<NextSeo>` of each page component. `nofollow` is also the same.
Also, the test case have expected wrong result. This PR fixes it.
=> Fix default robots overriding

src/jsonld/product.tsx
- Add `category` property to `ProductJsonLdProps` type – ensuring the Product props are defined according to https://schema.org/Product 
---
--> As it's a single optional prop type, no additional tests are necessary.
[ ] Updated the documentation
[ ] Unit/Cypress test covering all cases
- https://schema.org/Product 
=> Add cateogry property to product json-ld prop type

src/jsonld/jobPosting.tsx
The subfields of the Place interface for JobPostingJsonLd , other than addressCountry, are optional per google spec: https://developers.google.com/search/docs/appearance/structured-data/job-posting#basesalary:~:text=Include%20as%20many%20properties%20as%20possible.%20The%20more%20properties%20you%20provide%2C%20the%20higher%20quality%20the%20job%20posting%20is%20to%20our%20users.%20Note%20that%20you%20must%20include%20the%20addressCountry%20property
=> Make sub fields for Place on JobPostingJsonLd optional

README.md, src/types.ts, src/utils/schema/__tests__/setAggregateRating.test.ts, src/utils/schema/setAggregateRating.ts
Fixes #1118 
- Added worstRating under AggregateRating type & schema. Also added in tests & documentation.
---
=> fix: #1118 - added worstRating under AggregateRating type

README.md, cypress/e2e/campground.spec.js, cypress/schemas/campground-schema.js, cypress/schemas/index.js, e2e/pages/jsonld/campground/index.tsx, e2e/pages/jsonld/campground/multipleAmenityFeatures.tsx, e2e/pages/jsonld/index.tsx, src/index.tsx, src/jsonld/campground.tsx, src/types.ts, src/utils/schema/__tests__/setAmenityFeature.test.ts, src/utils/schema/setAmenityFeature.ts
Adding [Campground](https://schema.org/Campground) schema
---
[X] Updated the documentation
[X] Unit/Cypress test covering all cases
https://schema.org/Campground
=> feature: add CampgroundJsonLd component

cypress/schemas/common.js, cypress/schemas/local-business-schema.js, cypress/schemas/social-profile-schema.js, e2e/pages/jsonld/imageArray.tsx, src/jsonld/image.tsx
Changed the spelling of word "organisation" to "organization" as per https://schema.org/ and https://search.google.com/test/rich-results
Images For Reference:
Links For Reference:
https://validator.schema.org/
https://schema.org/
https://schema.org/creator
=> Changed Spelling of Organisation to Organization

cypress/e2e/norobots.spec.js, e2e/pages/_app.tsx, e2e/pages/norobots/index.tsx, e2e/pages/norobots/nofollow.tsx, e2e/pages/norobots/noindex.tsx, e2e/pages/norobots/robots.tsx, src/meta/buildTags.tsx, src/meta/defaultSEO.tsx, src/types.ts
Closes #985 
This feature adds a new "norobots" prop to `DefaultSEO` which removes the default robots meta tag inserted on all pages. 
---
=> feat: Remove default "robots" meta

README.md, cypress/e2e/qaPage.spec.js, e2e/pages/jsonld/qaPage.tsx, src/jsonld/__tests__/qaPage.spec.tsx, src/jsonld/qaPage.tsx, src/types.ts
---
Allow `QAPage` to set author URL if exists. Right now the current behavior would only set the name for the author but in order to improve the SEO we allow now setting the author with name and url if object is passed on (or you can just set the author as a string and it will set the proper structure with the name only) by reusing the `setAuthor` function logic.
---
[x] Updated the documentation
https://developers.google.com/search/docs/appearance/structured-data/qapage …
=> feat: Allow QAPage to set URL for author
