package.json
Removes the following:
> warning " > next-seo@1.0.1" has incorrect peer dependency "next@^6.0.0".
> warning " > next-seo@1.0.1" has incorrect peer dependency "react-dom@16.0.0".
=> 📦️ peerDependencies: next, reactdom

src/meta/__tests__/buildTags.test.jsx, src/meta/buildTags.jsx
fixes #5 
Include title template
=> inlcude title template

CHANGELOG.md, README.md, dist/index.js, dist/jsonld/socialProfile.js, e2e/cypress/e2e/jsonld.spec.js, e2e/cypress/schemas/index.js, e2e/cypress/schemas/social-profile-schema.js, e2e/package-lock.json, e2e/package.json, e2e/pages/jsonld.jsx, package.json, src/index.js, src/jsonld/socialProfile.jsx
This PR adds the ability to add JSON-LD for [Social Profiles](https://developers.google.com/search/docs/data-types/social-profile).
Closes #20
=> Add Social Profile JSON-LD

README.md, e2e/cypress/e2e/jsonld.spec.js, e2e/cypress/schemas/index.js, e2e/cypress/schemas/logo-schema.js, e2e/pages/jsonld.jsx, src/index.js, src/jsonld/logo.jsx
Implement logo as found in the [google structure data documentation](https://developers.google.com/search/docs/data-types/logo)
Related to #23
=> Add JSON LD logo support 

README.md, e2e/cypress/e2e/jsonld.spec.js, e2e/cypress/schemas/breadcrumb-schema.js, e2e/cypress/schemas/index.js, e2e/pages/jsonld.jsx, src/index.js, src/jsonld/breadcrumb.jsx
[Breadcrumb](https://developers.google.com/search/docs/data-types/breadcrumb)
=> Add support for JSON LD breadcrumb

src/jsonld/corporateContact.jsx, src/jsonld/localBusiness.jsx, src/jsonld/product.jsx, src/utils/formatIfArray.js
- check if a string or array is passed before formatting.
fixes #56
=> fix issue with checking if value is an array

cypress/e2e/seo.spec.js, e2e/pages/video.tsx, src/meta/__tests__/buildTags.spec.tsx, src/meta/buildTags.tsx, src/types.ts
Hi, it looks like this is your main WIP branch and I was interested in adding support for video object types in open graph following http://ogp.me/ .  I haven't tried running any of the tests but let me know if there's instructions for doing so in this newly structured branch. Or let me know what you think, thanks!
=> add support for og video object type

README.md, e2e/cypress/e2e/jsonld.spec.js, e2e/cypress/schemas/index.js, e2e/cypress/schemas/job-posting-schema.js, e2e/package-lock.json, e2e/package.json, e2e/pages/jsonld.jsx, package-lock.json, src/index.js, src/jsonld/jobPosting.jsx
Include support to [job posting](https://developers.google.com/search/docs/data-types/job-posting) and corresponding tests and documentation
=> Add support for Job Posting JSON-LD

README.md, cypress/e2e/seo.spec.js, e2e/pages/overridden.tsx, src/meta/nextSEO.tsx
Fixes https://github.com/garmeeh/next-seo/issues/97
-fix is change in src/meta/nextSEO.tsx
-added test coverage for this in override page, no existing/previous tests would catch this issue
-unrelated but moved the video seo test to be under the 'describe' so it is displayed in the group in cypress with other seo tests
=> fix mobile and language alternate in nextseo component

src/jsonld/localBusiness.tsx
Adding rating and priceRange field so it can be used for Restaurant schema.
https://schema.org/priceRange
https://schema.org/aggregateRating
=> Add rating and price range in localBusiness for Restaurant

cypress/e2e/jsonld.spec.js, cypress/schemas/breadcrumb-schema.js, e2e/pages/jsonld.tsx, src/jsonld/breadcrumb.tsx
Fixes #95 
---
[Contributing Guide](CONTRIBUTING.md)
=> fix: Fixes #95 breadcrumb issue

pull_request_template.md
---
[Contributing Guide](CONTRIBUTING.md)
=> Add better link in PR Template

src/meta/__tests__/__snapshots__/buildTags.spec.tsx.snap, src/meta/__tests__/buildTags.spec.tsx, src/meta/buildTags.tsx, src/meta/defaultSEO.tsx, src/meta/nextSEO.tsx, src/types.ts
Closes https://github.com/garmeeh/next-seo/issues/114
=> Multiple alternate languages

README.md, cypress/e2e/jsonld.spec.js, cypress/schemas/common.js, e2e/pages/jsonld.tsx, src/jsonld/product.tsx
Added 'url' field to 'offers' in ProductJsonLd, as recommended by Google.
=> add 'url' to 'offers' in ProductJsonLd

README.md, cypress/e2e/jsonld.spec.js, cypress/schemas/index.js, cypress/schemas/newsarticle-schema.js, e2e/pages/jsonld.tsx, src/index.tsx, src/jsonld/newsarticle.tsx
extend  NewsArticle from Article json-ld
=> add NewsArticle json-ld

README.md, cypress/e2e/jsonld.spec.js, cypress/schemas/faq-page-schema.js, cypress/schemas/index.js, e2e/pages/jsonld.tsx, src/index.tsx, src/jsonld/faqPage.tsx
Include support for [FAQ Page](https://developers.google.com/search/docs/data-types/faqpage) and corresponding tests and documentation.
=> Added support for FAQ Page JSON-LD

README.md, cypress/e2e/jsonld.spec.js, cypress/schemas/index.js, cypress/schemas/job-posting-schema.js, e2e/pages/jsonld.tsx, src/index.tsx, src/jsonld/jobPosting.tsx
Added JsonLd for JobPosting.
The code is taken from the 1.x branch and converted to typescript.
Kudos to @ctxquention for original work.
This will solve https://github.com/garmeeh/next-seo/issues/135
=> Added jsonld for jobposting.

README.md
Added documentation for properties to course.
=> Added documentation for course properties.

.github/workflows/tests.yml
=> Check if ubuntu version broke tests.yml

README.md
=> Fixed spelling mistake in readme.

README.md
Added downloads badge to readme.
=> Added downloads badge to readme.

README.md, cypress/e2e/jsonld.spec.js, cypress/schemas/address.js, cypress/schemas/event-schema.js, cypress/schemas/index.js, cypress/schemas/local-business-schema.js, e2e/pages/jsonld.tsx, src/index.tsx, src/jsonld/event.tsx, src/jsonld/localBusiness.tsx, src/types.ts, src/utils/buildAddress.ts
1. Added EventJsonLd component
2. Made address type an interface so it can be reused
3. Moved buildAddress function into a separate file so it can be reused
4. Updated README.md
=> feat: add EventJsonLd component

README.md
Minor. The documentation was missing the named export change.
=> Documentation missing the named export update

package.json
I'm sorry! I accidentally copied the Next.js v1 dependency.
Resolve #407
https://jubianchi.github.io/semver-check/#/^8.1.1-canary.54%20||%20^9.0.0/9.4.4
=> Fix invalid peerDependencies

src/jsonld/localBusiness.tsx
=> Fix invalid output

src/utils/minifyJsonLd.ts
At v4.10.0, I've faced a critical issue using `<~JsonLd>` components.
```
unexpected token /empty/ in JSON
```
To fix, I added a function to remove special/hidden characters to `minifyJsonLd`.
=> Remove special/hidden characters from jsonLd

README.md, cypress/e2e/jsonld.spec.js, cypress/schemas/job-posting-schema.js, e2e/pages/jsonld.tsx, src/jsonld/jobPosting.tsx
`hiringOrganization.logo` is added to Job Posting jsonld. 
[https://developers.google.com/search/docs/data-types/job-posting#hiring](https://developers.google.com/search/docs/data-types/job-posting#hiring)
Closes #475 
---
- Have you updated the documentation to go with your changes? Yes
- Have you written or updated unit tests? Yes
- Have you written an integration test in the test app supplied? Yes
=> feature: add logo to jobPosting jsonld

README.md, cypress/e2e/jsonld.spec.js, e2e/pages/jsonld.tsx, src/jsonld/article.tsx, src/jsonld/blog.tsx, src/jsonld/breadcrumb.tsx, src/jsonld/corporateContact.tsx, src/jsonld/course.tsx, src/jsonld/localBusiness.tsx, src/jsonld/logo.tsx, src/jsonld/newsarticle.tsx, src/jsonld/product.tsx, src/jsonld/socialProfile.tsx
I missed this PR 👉 #137 so re-adding.
Original changes made by @mikestopcontinues. 
---
=> Allow for multiple copies of json-ld elements by specifying keyOverride

README.md, cypress/e2e/jsonld.spec.js, cypress/schemas/article-schema.js, cypress/schemas/blog-schema.js, cypress/schemas/common.js, cypress/schemas/newsarticle-schema.js, e2e/pages/jsonld.tsx, src/jsonld/article.tsx, src/jsonld/blog.tsx, src/jsonld/newsarticle.tsx, src/jsonld/recipe.tsx, src/utils/formatAuthorName.ts
closes #481
Support multiple authors in articles, blogs, news articles and recipes.
---
- Have you updated the documentation to go with your changes? yes
- Have you written or updated unit tests? yes
- Have you written an integration test in the test app supplied? yes
=> feature: multiple authors in JSON-LD

README.md
Per resolution to https://github.com/garmeeh/next-seo/issues/507#issuecomment-707273960
---
=> docs: note about required order of DefaultSeo and Component

src/jsonld/article.tsx, src/jsonld/blog.tsx, src/jsonld/breadcrumb.tsx, src/jsonld/carousel.tsx, src/jsonld/corporateContact.tsx, src/jsonld/course.tsx, src/jsonld/dataset.tsx, src/jsonld/event.tsx, src/jsonld/faqPage.tsx, src/jsonld/jobPosting.tsx, src/jsonld/localBusiness.tsx, src/jsonld/logo.tsx, src/jsonld/newsarticle.tsx, src/jsonld/product.tsx, src/jsonld/recipe.tsx, src/jsonld/socialProfile.tsx, src/utils/minifyJsonLd.ts
As highlighted in #514 & #515, the minify json method introduced a small bug that could be affecting sites negatively. To avoid any further delay in getting a fix out I am reverting the feature until it can be looked into more.    
---
=> Remove Minify JSON

package.json
The tests with Next.js 10 passed in this PR https://github.com/garmeeh/next-seo/pull/554.
=> Add Next.js 10 peer dependency

README.md, src/jsonld/localBusiness.tsx
Add the the type of cuisine the restaurant serves.
=> Add optional servesCuisine

package.json
I'm having problems installing this package in a project with React 17:
```
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.0.0" from next-seo@4.15.0
npm ERR! node_modules/next-seo
npm ERR!   next-seo@"*" from the root project
```
Given React 17 introduces no new features, I believe this won't cause any problem.
Thanks for your work on `next-seo`!
=> Update package.json to support version 17 of react and react-dom

README.md, cypress/e2e/jsonld.spec.js, cypress/schemas/index.js, cypress/schemas/site-links-search-box-schema.js, e2e/pages/jsonld.tsx, src/index.tsx, src/jsonld/siteLinksSearchBox.tsx
- Implemented Sitelinks Search Box schema
- Wrote e2e tests and made sure all passed
- Updated README with links and a working example
#539
=> Implement Sitelinks Search Box schema

README.md, src/jsonld/jobPosting.tsx
Updated property `jobLocation` at `JobPostingJsonLdProps` to make it optional, this solves the issue (#548).
Also the docs for the property were updated and moved from **Required properties** to **Supported properties**.
---
Have you updated the documentation to go with your changes? **Yes**
Have you written or updated unit tests? **No**
Have you written an integration test in the test app supplied? **No**
=> Updated jobLocation as optional

.github/stale.yml
Stale bot was a little too aggressive on closing issues. 
---
=> Update Stale Bot Rules

README.md, src/jsonld/carousel.tsx, src/utils/buildVideo.ts
The movie directors could be more than one Person object
=> Add multiple directors support in movie carousel

README.md, cypress/e2e/jsonld.spec.js, cypress/schemas/local-business-schema.js, e2e/pages/jsonld.tsx, src/jsonld/localBusiness.tsx
As we can see the review list is a [recommended prop by google](https://developers.google.com/search/docs/data-types/local-business) so this PR will add it as an optional prop in LocalBusiness JSON-LD. I added the exact properties used in schem.org examples for [Review](https://schema.org/Review) and for [Rating](https://schema.org/Rating), i'm open to add another properties if needed.
---
- Have you updated the documentation to go with your changes?  ✅
- Have you written or updated unit tests? ✅
- Have you written an integration test in the test app supplied? ✅
=> [Feature] add reviews to local bussines json ld

README.md
Grammar fixes and clarity improvements in README.md
=> Docs: Grammar fixes [README.md]

.eslintrc, README.md, e2e/.babelrc, e2e/pages/_app.tsx, e2e/pages/robots.tsx, package.json, src/meta/defaultSEO.tsx, src/meta/nextSEO.tsx, yarn.lock
=> Tidy up for Next v11.0.0

README.md, cypress/e2e/jsonld.spec.js, cypress/schemas/common.js, cypress/schemas/course-schema.js, cypress/schemas/index.js, cypress/schemas/recipe-schema.js, cypress/schemas/videogame-schema.js, e2e/pages/jsonld.tsx, src/index.tsx, src/jsonld/carousel.tsx, src/jsonld/product.tsx, src/jsonld/recipe.tsx, src/jsonld/softwareApp.tsx, src/jsonld/videoGame.tsx, src/types.ts, src/utils/buildAggregateRating.tsx, src/utils/buildReviews.tsx
Closes: #767.
- New `VideoGame` schema type support.
- Tests for `VideoGame` schema type.
- Tweaks for some test files.
=> feat: `VideoGame` schema type support

README.md
Closes: #771 
This PR updates `README.md` with correct `Next.js` custom app documentation link
---
- Have you updated the documentation to go with your changes? ✅
=> Update Next.js custom app documentation link

README.md
=> Fixed some copy-paste oversight

src/jsonld/recipe.tsx
=> Fix buildInstruction function

README.md, cypress/e2e/jsonld.spec.js, cypress/schemas/brand-schema.js, cypress/schemas/contactPoint.js, cypress/schemas/corporate-contact-schema.js, cypress/schemas/index.js, cypress/schemas/organization-schema.js, cypress/schemas/web-page-schema.js, e2e/next-env.d.ts, e2e/pages/jsonld.tsx, src/index.tsx, src/jsonld/brand.tsx, src/jsonld/corporateContact.tsx, src/jsonld/organization.tsx, src/jsonld/webPage.tsx, src/types.ts
Adding [Organization](https://schema.org/Organization) schema, there is [a feature request](https://github.com/garmeeh/next-seo/issues/854), also 2 more types, [WebPage](https://schema.org/WebPage) and [Brand](https://schema.org/Brand)
P.S. For organization I allowed the type to be configurable with the default 'Organization', as i needed only the 'Corporation' but maybe other will need other types. 
---
- Have you updated the documentation to go with your changes? ✅
- Have you written or updated unit tests? ✅
- Have you written an integration test in the test app supplied? ✅ …
=> [Feature] - OrganizationJsonLD & WebPageJsonLd & BrandJsonLd

README.md
Fixed `NextSeo Options` section
=> Fix README.md tables

src/utils/schema/setReviews.ts
Removed a `console.log` from setReviews! It's flooding my local and prod env 😅
=> Remove console.log from setReviews

cypress/e2e/webPageJsonLd.spec.js, e2e/pages/jsonld/webPage2.tsx, src/jsonld/webPage.tsx, src/types.ts, src/utils/schema/setReviewedBy.ts
Although there are recommended property in the document, the `reviewedBy` field is optional because it seems to be a mandatory field.
Example;
https://jsonld.com/web-page/
- Have you updated the documentation to go with your changes? **Yes**
- Have you written or updated unit tests? **Yes**
All tests are passing.
=> chore: `reviewedBy` field for WebPageJsonLd has been changed to optional

src/index.tsx
Export `SocialProfileJsonLdProps` type.
Fixes #928
=> Fix missing `SocialProfileJsonLdProps` export

README.md, cypress/e2e/article.spec.js, e2e/pages/jsonld/article.tsx, e2e/pages/jsonld/articleOld.tsx, src/jsonld/article.tsx, src/types.ts, src/utils/schema/setAuthor.ts
minimal modification
before
after
---
=> feat: support article author url

README.md, src/index.tsx, src/meta/__tests__/__snapshots__/buildTags.spec.tsx.snap, src/meta/__tests__/buildTags.spec.tsx, src/meta/buildTags.tsx, src/types.ts, yarn.lock
This PR will add support for the og:audio parameter.
[OGP Specifications](https://ogp.me/#structured)
---
=> Add support for 'og:audio'

jest.config.js, jest.setup.js, package.json, src/jsonld/__tests__/dataset.spec.tsx, src/jsonld/__tests__/logo.spec.tsx, src/jsonld/jsonld.tsx, src/meta/__tests__/buildTags.spec.tsx, src/utils/toJson.tsx, yarn.lock
To further backup the end to tests that are in place via Cypress, over the coming weeks will be looking to increase test coverage via Jest. 
---
=> Increase Test Coverage

.github/workflows/jest.yml, src/jsonld/__tests__/logo.spec.tsx
=> Add jest action

cypress/e2e/image.spec.js, cypress/schemas/image-schema.js, cypress/schemas/index.js, cypress/schemas/job-posting-schema.js, e2e/pages/jsonld/image.tsx, e2e/pages/jsonld/imageArray.tsx, src/index.tsx, src/jsonld/__tests__/image.spec.tsx, src/jsonld/image.tsx, src/jsonld/jsonld.tsx, src/utils/toJson.tsx, yarn.lock
This PR adds an `ImageJsonLd` component which can accept properties at the top level for one image, or an array in an `images` array in order to cater for multiple images.
The `toJson` function also had to be modified in order to make this possible.
---
=> adds image jsonld

cypress/e2e/localBusiness.spec.js, cypress/e2e/organization.spec.js, cypress/schemas/local-business-schema.js, cypress/schemas/organization-schema.js, e2e/pages/jsonld/localBusiness/localBusiness.tsx, e2e/pages/jsonld/localBusiness/multipleAddresses.tsx, e2e/pages/jsonld/localBusiness/singleAddressArray.tsx, e2e/pages/jsonld/organization/multipleAddresses.tsx, e2e/pages/jsonld/organization/organization.tsx, src/jsonld/localBusiness.tsx, src/jsonld/organization.tsx, src/utils/schema/setAddress.ts
Fixes #983 
* Support multiple addresses for Local Business and Organization ([relevant StackExchange question](https://webmasters.stackexchange.com/questions/81735/multiple-addresses-in-json-ld-schema-org))
---
=> feat(983): support multiple addresses for Local Business and Organization

README.md
=> Docs for ImageJson

src/jsonld/breadcrumb.tsx
fixes #1039
support for additional props added to BreadcrumbJsonLd
=> fix: BreadcrumbJsonLd additional property

src/jsonld/webPage.tsx
=> [1111] Improve WebPageJsonLdProps by extending JsonLdProps

README.md
=> [1109] Fix WebPage docs link

src/meta/__tests__/buildTags.spec.tsx, src/meta/buildTags.tsx
=> Revert "Fix default robots overriding"

README.md
=> Fix useAppDir prop value instructions when using app dir

README.md, cypress/e2e/park.spec.js, cypress/schemas/index.js, cypress/schemas/park-schema.js, e2e/pages/jsonld/index.tsx, e2e/pages/jsonld/park.tsx, src/index.tsx, src/jsonld/park.tsx
Adding [Park](https://schema.org/Park) schema
---
[X] Updated the documentation
[X] Unit/Cypress test covering all cases
https://schema.org/Park
=> feature: add ParkJsonLd component

cypress/e2e/breadcrumb.spec.js, cypress/e2e/profilePage.spec.js, package.json, src/utils/schema/setItemListElements.ts
=> Fix properties BreadCrumbJsonLdProps

package.json
Previous changes did resolve the original issue so reverting for now. Based on this comment seems like original issue may not be present https://github.com/garmeeh/next-seo/issues/1495#issuecomment-2890746406
=> Revert Previous Changes

cypress/e2e/product.spec.js, e2e/pages/product-jsonld/aggregateOffer.tsx, e2e/pages/product-jsonld/aggregateOffer2.tsx, e2e/pages/product-jsonld/aggregateOfferAndOffers.tsx, e2e/pages/product-jsonld/offers.tsx, src/types.ts, src/utils/schema/setOffers.ts
Added support for `offer.hasMerchantReturnPolicy` based on https://schema.org/hasMerchantReturnPolicy
---
=> gijsbotje:Feature/offers-hasMerchantReturnPolicy
